Repository WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-afac974, pull requests merged in 2024-08, with the labels that each got.

#3 Add join in ArtworkRepository
  server/database/models/ArtworkRepository.js
  server/database/schema.sql
Labels: REVIEWED

#5 change path for image_url
  server/database/schema.sql
  server/public/assets/images/PicturesTest/ImageTest1.png
  server/public/assets/images/PicturesTest/ImageTest2.jpg
  server/public/assets/images/PicturesTest/ImageTest3.jpg
Labels: REVIEW REQUESTED

#4 Allartistspage
  client/package.json
  client/src/App.jsx
  client/src/assets/styles/artistlist.css
  client/src/components/ArtistComponent.jsx
  client/src/main.jsx
  client/src/pages/ArtistList.jsx
  client/src/services/request.js
  server/app/config.js
  server/package.json
Labels: CORRECTIONS DONE
