Repository WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-afac974, pull requests merged in 2024-09, with the labels that each got.

#8 Firstcrud
  server/app/controllers/artistActions.js
  server/app/controllers/artworkActions.js
  server/app/router.js
  server/database/models/ArtistRepository.js
  server/database/models/ArtworkRepository.js
Labels: CONFLICTS RESOLVED, REVIEWED

#7 create page ArtworkPage.jsx for one artwork with back and front
  client/src/App.jsx
  client/src/assets/styles/artworkpage.css
  client/src/main.jsx
  client/src/pages/ArtworkPage.jsx
  client/src/services/request.js
  package-lock.json
  server/app/config.js
  server/public/assets/images/logo_house.png
Labels: CONFLICTS RESOLVED, CORRECTIONS DONE

#12 creation of db and route for expo
  server/app/controllers/exhibitionActions.js
  server/app/router.js
  server/database/models/ExhibitionRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: CORRECTIONS DONE, REVIEWED

#13 T6/feat/frontend/formular
  README.md
  client/package-lock.json
  client/src/App.css
  client/src/assets/.gitkeep
  client/src/assets/font/Montserrat-Regular.ttf
  client/src/assets/images/VirtuArtLogo.svg
  client/src/assets/styles/artworkpage.css
  client/src/assets/styles/homepage.css
  client/src/components/.gitkeep
  client/src/components/ArtworkComponent.jsx
  client/src/components/Navbar.jsx
  client/src/main.jsx
  client/src/pages/.gitkeep
  client/src/pages/ArtistsPage.jsx
  client/src/pages/ArtworkPage.jsx
  client/src/pages/ArtworksPage.jsx
  client/src/pages/ExhibitionPage.jsx
  client/src/pages/Homepage.jsx
  package-lock.json
  server/app/config.js
  server/database/models/ArtworkRepository.js
  server/database/schema.sql
  server/package-lock.json
  server/public/assets/images/PicturesTest/ImageTest1.jpg
  server/public/assets/images/PicturesTest/ImageTest2.jpg
  server/public/assets/images/PicturesTest/ImageTest3.jpg
  server/public/assets/images/VirtuArtLogo.png
Labels: CORRECTIONS DONE, REVIEWED

#14 add route for join table
  server/app/controllers/exhibitionActions.js
  server/app/router.js
  server/database/models/ExhibitionRepository.js
  server/database/schema.sql
Labels: CORRECTIONS DONE, REVIEWED

#15 Create userPage, navbar outside of outlet and link to all artworks
  client/src/App.jsx
  client/src/assets/images/add_image30px.png
  client/src/components/Navbar.jsx
  client/src/main.jsx
  client/src/pages/ArtworksPage.jsx
  client/src/pages/Homepage.jsx
  client/src/pages/UserPage.jsx
  server/app/controllers/exhibitionActions.js
  server/app/router.js
  server/database/models/ExhibitionRepository.js
Labels: REVIEWED

#16 Feat/t6/artist page
  client/src/assets/styles/artistprofile.css
  client/src/assets/styles/artworkpage.css
  client/src/assets/styles/homepage.css
  client/src/components/ArtworkComponent.jsx
  client/src/components/Navbar.jsx
  client/src/main.jsx
  client/src/pages/ArtistList.jsx
  client/src/pages/ArtistPage.jsx
  client/src/pages/ArtistsPage.jsx
  client/src/pages/ArtworkPage.jsx
  client/src/pages/ArtworksPage.jsx
  client/src/pages/Homepage.jsx
  client/src/services/request.js
  server/app/controllers/artworkActions.js
  server/app/router.js
  server/database/models/ArtworkRepository.js
  server/database/schema.sql
Labels: REVIEW REQUESTED

#17 Form component to add new artworks from user page, only visual render…
  client/src/assets/styles/artworkForm.css
  client/src/assets/styles/homepage.css
  client/src/assets/styles/userpage.css
  client/src/components/ArtworkForm.jsx
  client/src/components/Navbar.jsx
  client/src/main.jsx
  client/src/pages/UserPage.jsx
  server/database/schema.sql
Labels: REVIEWED

#18 Exhibition page
  client/src/assets/styles/exhibition.css
  client/src/components/ExhibitionComponent.jsx
  client/src/main.jsx
  client/src/pages/Exhibition.jsx
  client/src/pages/ExhibitionPage.jsx
  client/src/pages/Homepage.jsx
  client/src/services/request.js
  server/database/schema.sql
Labels: CONFLICTS RESOLVED, REVIEWED

#19 Create ExhibitionForm for add and delete artwork in exhibition
  client/src/components/exhibitionForm/AddArtworkComponent.jsx
  client/src/components/exhibitionForm/ExhibitionComponent.jsx
  client/src/main.jsx
  client/src/pages/ExhibitionForm.jsx
  client/src/services/request.js
  server/app/router.js
  server/database/models/ExhibitionRepository.js
Labels: REVIEWED

#23 Feat/backend authentification
  server/app/controllers/authActions.js
  server/app/controllers/userActions.js
  server/app/router.js
  server/app/services/auth.js
  server/database/fixtures/ItemSeeder.js
  server/database/models/UserRepository.js
  server/database/schema.sql
  server/database/tables.js
  server/package.json
  server/public/assets/images/favicon.png
  server/public/assets/images/logo_house.png
Labels: REVIEW REQUESTED

#24 Feat: IconsComponent
  client/src/assets/icons/check.svg
  client/src/assets/icons/cross.svg
  client/src/assets/icons/empty-heart.svg
  client/src/assets/icons/error.svg
  client/src/assets/icons/eye-password-hide.svg
  client/src/assets/icons/eye-password-show.svg
  client/src/assets/icons/full-heart.svg
  client/src/assets/icons/key.svg
  client/src/assets/icons/left-arrow.svg
  client/src/assets/icons/lock.svg
  client/src/assets/icons/mail.svg
  client/src/assets/icons/right-arrow.svg
  client/src/assets/icons/tag.svg
  client/src/assets/icons/user.svg
  client/src/assets/images/background.webp
  client/src/assets/images/burger.png
  client/src/assets/images/hear50px.png
  client/src/assets/images/import.png
  client/src/assets/images/user50px.png
  client/src/components/IconsComponent.jsx
  client/src/components/exhibitionForm/AddArtworkComponent.jsx
  client/src/main.jsx
  client/src/pages/ExhibitionForm.jsx
Labels: REVIEW REQUESTED

#32 Fix: Navabar and UserPage, tested and work
  client/src/components/Navbar.jsx
  client/src/pages/UserPage.jsx
Labels: REVIEWED

#27 Refactor selection method
  client/src/components/exhibitionForm/AddArtworkComponent.jsx
  client/src/components/exhibitionForm/ExhibitionComponent.jsx
  client/src/main.jsx
  client/src/pages/ExhibitionForm.jsx
  client/src/services/request.js
Labels: CONFLICTS RESOLVED, REVIEWED

#26 Refactor: add files css, update files for css
  client/src/App.css
  client/src/App.jsx
  client/src/assets/styles/authentification_styles/authpage.css
  client/src/assets/styles/authentification_styles/backbuttoncomponent.css
  client/src/assets/styles/authentification_styles/loginpage.css
  client/src/assets/styles/authentification_styles/registerpage.css
  client/src/assets/styles/authentification_styles/toggleswitchcomponent.css
  client/src/assets/styles/homepage.css
  client/src/assets/styles/navbarcomponent.css
  client/src/components/ArtworkForm.jsx
  client/src/components/NavbarComponent.jsx
  client/src/main.jsx
  client/src/pages/ArtistList.jsx
  client/src/pages/ArtistPage.jsx
  client/src/pages/ArtworkPage.jsx
  client/src/pages/Exhibition.jsx
  client/src/pages/Homepage.jsx
  client/src/pages/UserPage.jsx
Labels: CONFLICTS RESOLVED, CORRECTIONS DONE, REVIEWED

#34 change image path for the defitiv version of artwork
  server/database/schema.sql
  server/public/assets/images/PicturesTest/Algorithme_de_Vie .webp
  server/public/assets/images/PicturesTest/Chaos_Organisé.webp
  server/public/assets/images/PicturesTest/Connexion.webp
  server/public/assets/images/PicturesTest/Douce_Mélancolie.webp
  server/public/assets/images/PicturesTest/Echo_de_Lumière.webp
  server/public/assets/images/PicturesTest/Eclosion.webp
  server/public/assets/images/PicturesTest/Equilibre.webp
  server/public/assets/images/PicturesTest/Esprit_Ancien.webp
  server/public/assets/images/PicturesTest/Fleurs_de_Soie.webp
  server/public/assets/images/PicturesTest/Forêt_de_Tissus.webp
  server/public/assets/images/PicturesTest/Fractale.webp
  server/public/assets/images/PicturesTest/Fragments_Urbains.webp
  server/public/assets/images/PicturesTest/Fusion.webp
  server/public/assets/images/PicturesTest/Fusion_Minérale.webp
  server/public/assets/images/PicturesTest/Harmonie.webp
  server/public/assets/images/PicturesTest/ImageTest1.jpg
  server/public/assets/images/PicturesTest/ImageTest2.jpg
  server/public/assets/images/PicturesTest/ImageTest3.jpg
  server/public/assets/images/PicturesTest/Joie_Ephémère.webp
  server/public/assets/images/PicturesTest/Lumière_dans_Obscurité,.webp
  server/public/assets/images/PicturesTest/Lumières_Réactives.webp
  server/public/assets/images/PicturesTest/Mémoire_Digitale.webp
  server/public/assets/images/PicturesTest/Métamorphose.webp
  server/public/assets/images/PicturesTest/Nouveau_Souffle.webp
  server/public/assets/images/PicturesTest/Odyssée.webp
  server/public/assets/images/PicturesTest/Ondulations.webp
  server/public/assets/images/PicturesTest/Passages.webp
  server/public/assets/images/PicturesTest/Reflets.webp
  server/public/assets/images/PicturesTest/Regards_Perdus.webp
  server/public/assets/images/PicturesTest/Révolution_Numérique.webp
  server/public/assets/images/PicturesTest/Terre_et_Mer.webp
  server/public/assets/images/PicturesTest/Vase_Organique.webp
  server/public/assets/images/PicturesTest/Vie_Urbaine.webp
Labels: REVIEWED

#28 create full back-end for favorites page CRUD test with postman query
  client/src/assets/styles/favorites.css
  client/src/assets/styles/homepage.css
  client/src/components/NavbarComponent.jsx
  client/src/components/exhibitionForm/AddArtworkComponent.jsx
  client/src/components/exhibitionForm/ExhibitionComponent.jsx
  client/src/main.jsx
  client/src/pages/ExhibitionForm.jsx
  client/src/pages/Favorite.jsx
  server/app/controllers/favoriteActions.js
  server/app/router.js
  server/database/models/FavoriteRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: CONFLICTS RESOLVED, CORRECTIONS DONE

#20 Us02 artwork form
  client/src/components/ArtworkForm.jsx
  client/src/components/NavbarComponent.jsx
  package-lock.json
  server/app/config.js
  server/app/router.js
  server/app/services/middleware.js
  server/database/models/ArtworkRepository.js
  server/database/schema.sql
  server/package.json
  server/public/uploads/66eaa5cc-d44c-40b3-a7a7-a3763c763481.jpg
  server/public/uploads/6d9a753f-2173-4be8-ae2b-ca0280983897.jpg
  server/public/uploads/coucou
  server/public/uploads/puente_1.jpg
Labels: CHANGES REQUESTED, CONFLICTS

#30 Feat: Authentification Frontend (pages, context, component)
  client/src/App.jsx
  client/src/assets/favicon.ico
  client/src/assets/styles/authentification_styles/loginpage.css
  client/src/assets/styles/authentification_styles/registerpage.css
  client/src/assets/styles/authentification_styles/toggleswitchcomponent.css
  client/src/components/NavbarComponent.jsx
  client/src/components/authentification_components/BackButtonComponent.jsx
  client/src/components/authentification_components/SentencePasswordCheckComponent.jsx
  client/src/context/AuthContext.jsx
  client/src/main.jsx
  client/src/pages/UserPage.jsx
  client/src/pages/authentification_pages/AuthPage.jsx
  client/src/pages/authentification_pages/LoginPage.jsx
  client/src/pages/authentification_pages/RegisterPage.jsx
  client/src/services/request.js
  server/app/controllers/authActions.js
  server/app/controllers/userActions.js
  server/app/services/middleware.js
  server/database/models/UserRepository.js
  server/database/schema.sql
  server/package-lock.json
Labels: CONFLICTS RESOLVED, CORRECTIONS DONE

#36 Upload image from form
  client/src/components/ArtworkForm.jsx
  server/public/uploads/d3bf6342-9b96-4784-b921-531189218342.jpg
  server/public/uploads/f4d65626-86e6-4851-8229-9737239f09d3.jpg
Labels: REVIEW REQUESTED, REVIEWED

#37 Masonry exhibition form
  client/package.json
  client/src/assets/styles/exhibitionForm.css
  client/src/components/exhibitionForm/ExhibitionComponent.jsx
  server/database/schema.sql
  server/public/assets/images/PicturesTest/Algorithme_de_Vie.webp
  server/public/assets/images/PicturesTest/Lumière_dans_Obscurité.webp
Labels: REVIEWED

#31 Carousel homepage
  client/src/assets/styles/homepage.css
  client/src/components/CarouselHomepage.jsx
  client/src/main.jsx
  client/src/pages/Homepage.jsx
Labels: REVIEWED

#38 Update exhibition form
  client/src/assets/styles/confirmButton.css
  client/src/assets/styles/exhibitionForm.css
  client/src/components/exhibitionForm/AddArtworkComponent.jsx
  client/src/components/exhibitionForm/ConfirmButton.jsx
  client/src/components/exhibitionForm/CreateExihibition.jsx
  client/src/components/exhibitionForm/ExhibitionComponent.jsx
  client/src/pages/ExhibitionForm.jsx
  client/src/services/request.js
  server/database/models/ExhibitionRepository.js
Labels: REVIEWED

#41 Artistlist css
  client/src/App.css
  client/src/assets/styles/artistlist.css
  client/src/components/ArtistComponent.jsx
  client/src/pages/ArtistList.jsx
Labels: REVIEWED

#40 Feat/user interface
  client/src/App.jsx
  client/src/assets/styles/authentification_styles/authpage.css
  client/src/assets/styles/user_connected_styles/personalinformationspage.css
  client/src/assets/styles/userpage.css
  client/src/components/NavbarComponent.jsx
  client/src/context/AuthContext.jsx
  client/src/main.jsx
  client/src/pages/UserPage.jsx
  client/src/pages/authentification_pages/AuthPage.jsx
  client/src/pages/authentification_pages/LoginPage.jsx
  client/src/pages/user_connected_pages/PersonalInformationsPage.jsx
  client/src/services/.gitkeep
  client/src/services/request.js
  server/app/controllers/userActions.js
  server/app/router.js
  server/database/models/UserRepository.js
  server/database/schema.sql
Labels: CHANGES REQUESTED

#45 Feature: favorite page now dynamic and CRUD working
  client/src/assets/styles/favorites.css
  client/src/components/FavoriteComponent.jsx
  client/src/components/NavbarComponent.jsx
  client/src/contexts/FavoritesContext.jsx
  client/src/main.jsx
  client/src/pages/ArtworkPage.jsx
  client/src/pages/Favorite.jsx
  client/src/services/request.js
  server/app/controllers/favoriteActions.js
  server/app/router.js
  server/app/services/auth.js
  server/database/schema.sql
Labels: REVIEWED

#43 css in homepage
  client/src/App.css
  client/src/assets/styles/artworkForm.css
  client/src/assets/styles/homepage.css
  client/src/components/ArtworkComponent.jsx
  client/src/components/ArtworkForm.jsx
  client/src/components/CarouselHomepage.jsx
  client/src/pages/authentification_pages/LoginPage.jsx
  server/app/services/middleware.js
  server/public/uploads/faa0570f-8373-4edf-a623-e0162b00297c.jpg
Labels: CONFLICTS RESOLVED

#46 Fix/authentifcation
  client/src/assets/icons/user-connected.svg
  client/src/components/IconsComponent.jsx
  client/src/components/NavbarComponent.jsx
  client/src/main.jsx
  client/src/pages/user_connected_pages/DashboardPage.jsx
Labels: CORRECTIONS DONE, REVIEWED

#50 Refactor:BackEndOnly
  server/app/controllers/artistActions.js
  server/app/router.js
  server/database/models/ArtistRepository.js
  server/database/models/ArtworkRepository.js
  server/database/models/ExhibitionRepository.js
  server/database/models/UserRepository.js
  server/database/schema.sql
  server/database/tables.js
  server/public/assets/avatar_user/Alice_Dupont.webp
  server/public/assets/avatar_user/David_Rodriguez.webp
  server/public/assets/avatar_user/Emma_Leger.webp
  server/public/assets/avatar_user/Etienne_Laurent.webp
  server/public/assets/avatar_user/Isabelle_Morel.webp
  server/public/assets/avatar_user/Lucas_Dubois.webp
  server/public/assets/avatar_user/Marc_Lefevre.webp
  server/public/assets/avatar_user/Maya_Nguyen.webp
  server/public/assets/avatar_user/Olivier_Martin_.webp
  server/public/assets/avatar_user/Sophia_Durand.webp
  server/public/assets/avatar_user/default.png
Labels: REVIEWED

#51 Refactor:Frontend change artist for user
  client/src/components/ArtistComponent.jsx
  client/src/components/ArtworkForm.jsx
  client/src/components/CarouselHomepage.jsx
  client/src/components/NavbarComponent.jsx
  client/src/main.jsx
  client/src/pages/ArtistList.jsx
  client/src/pages/ArtistPage.jsx
  client/src/pages/ArtworkPage.jsx
  client/src/pages/Homepage.jsx
  client/src/services/request.js
Labels: REVIEWED

#53 Fix1 : partie ADMIN droit, suppressions expositions
  client/src/components/exhibitionForm/ConfirmButton.jsx
  client/src/components/exhibitionForm/ConfirmationButton.jsx
  client/src/main.jsx
  client/src/services/request.js
  server/app/controllers/authActions.js
  server/app/router.js
  server/app/services/middleware.js
  server/public/assets/images/PicturesTest/3c239d00-584c-4e2d-9024-9e27e787365c.webp
Labels: REVIEWED

#54 Fix2
  client/src/assets/styles/navbarcomponent.css
  client/src/components/NavbarComponent.jsx
  client/src/services/request.js
  server/app/router.js
Labels: REVIEWED

#55 Fix3
  client/src/App.jsx
  client/src/components/ArtistComponent.jsx
  client/src/components/ArtworkForm.jsx
  client/src/components/CarouselHomepage.jsx
  client/src/components/NavbarComponent.jsx
  client/src/components/exhibitionForm/ConfirmationButton.jsx
  client/src/components/exhibitionForm/ExhibitionComponent.jsx
  client/src/contexts/AuthContext.jsx
  client/src/main.jsx
  client/src/pages/ArtworksPage.jsx
  client/src/pages/Favorite.jsx
  client/src/pages/Homepage.jsx
  client/src/pages/authentification_pages/AuthPage.jsx
  client/src/pages/authentification_pages/LoginPage.jsx
  client/src/pages/user_connected_pages/PersonalInformationsPage.jsx
  server/app/services/middleware.js
  server/database/models/UserRepository.js
  server/database/schema.sql
  server/public/assets/images/PicturesTest/3c239d00-584c-4e2d-9024-9e27e787365c.webp
  server/public/uploads/66eaa5cc-d44c-40b3-a7a7-a3763c763481.jpg
  server/public/uploads/6d9a753f-2173-4be8-ae2b-ca0280983897.jpg
  server/public/uploads/coucou
  server/public/uploads/d3bf6342-9b96-4784-b921-531189218342.jpg
  server/public/uploads/f4d65626-86e6-4851-8229-9737239f09d3.jpg
  server/public/uploads/faa0570f-8373-4edf-a623-e0162b00297c.jpg
  server/public/uploads/puente_1.jpg
Labels: REVIEWED
